### PR TITLE
Fix the bug existed in low_cardinality(nullable) type

### LINKED ISSUE #38: Problem existed in low_cardinality(nullable(types))
When using low_cardinality(nullable(types)), errors will occur. Including empty query, code error and data receive problem.
```%TESTC  1 v2
%TSTTREE2,com.timeplus.jdbc.type.LowCardinalityTypeTest,true,1,false,1,LowCardinalityTypeTest,,[engine:junit-jupiter]/[class:com.timeplus.jdbc.type.LowCardinalityTypeTest]
%TSTTREE3,testNullLowCardinalityTypes(com.timeplus.jdbc.type.LowCardinalityTypeTest),false,1,false,2,testNullLowCardinalityTypes(),,[engine:junit-jupiter]/[class:com.timeplus.jdbc.type.LowCardinalityTypeTest]/[method:testNullLowCardinalityTypes()]
%TESTS  3,testNullLowCardinalityTypes(com.timeplus.jdbc.type.LowCardinalityTypeTest)

%ERROR  3,testNullLowCardinalityTypes(com.timeplus.jdbc.type.LowCardinalityTypeTest)
%TRACES 
com.timeplus.exception.TimeplusSQLException: DB::ExceptionDB::Exception: Empty query. Stack trace:

        at com.timeplus.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:33)
        at com.timeplus.protocol.Response.readFrom(Response.java:35)
        at com.timeplus.client.NativeClient.receiveResponse(NativeClient.java:207)
        at com.timeplus.client.NativeClient.receiveEndOfStream(NativeClient.java:158)
        at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:294)
        at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.executeBatch(TimeplusPreparedInsertStatement.java:160)
        at com.timeplus.jdbc.type.LowCardinalityTypeTest.lambda$1(LowCardinalityTypeTest.java:135)
        at com.timeplus.jdbc.AbstractITestConnectDB.withStatement(AbstractITestConnectDB.java:137)
        at com.timeplus.jdbc.AbstractITestConnectDB.lambda$withStatement$0(AbstractITestConnectDB.java:142)
        at com.timeplus.jdbc.AbstractITestConnectDB.withNewConnection(AbstractITestConnectDB.java:125)
        at com.timeplus.jdbc.AbstractITestConnectDB.withStatement(AbstractITestConnectDB.java:142)
        at com.timeplus.jdbc.type.LowCardinalityTypeTest.testNullLowCardinalityTypes(LowCardinalityTypeTest.java:107)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
        at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
        Suppressed: java.sql.SQLException: Call getSampleBlock before insert.
                at com.timeplus.misc.Validate.isTrue(Validate.java:41)
                at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:289)
                at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.close(TimeplusPreparedInsertStatement.java:173)
                at com.timeplus.jdbc.type.LowCardinalityTypeTest.lambda$1(LowCardinalityTypeTest.java:136)
                ... 72 more

### PR DESCRIPTION
**Pull request by Jasmine-ge**
close #38

### CODE REVIEW

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 1]
```diff
@@ -53,16 +70,37 @@ public void flushToSerializer(BinarySerializer serializer, boolean immediate) th
...
+
         if (immediate) {
             /// The data layout: [version][index_type][dictionary][indexes]
             serializer.writeLong(version);
             serializer.writeLong(IndexType.UInt64.getValue() | IndexType.HasAdditionalKeysBit.getValue());
             serializer.writeLong(dict.size());
-            for (int i = 0; i < dict.size(); i++) {
-                data.write(dict.get(i));
+
+            if (data.type().nullable()) {
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:80]: use `nested_is_nullable`

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 2]
```diff
@@ -53,16 +70,37 @@ public void flushToSerializer(BinarySerializer serializer, boolean immediate) th
...
+                DataTypeNullable inside_column_type = (DataTypeNullable) type.type();
+                IDataType inside_type = inside_column_type.getNestedDataType();
+
+                for (int i = 0; i < dict.size(); i++) {
+                    Object temp = dict.get(i);
+                    if (temp == null) {
+                        inside_type.serializeBinary(inside_type.defaultValue(), serializer);
+                    }
+                    else {
+                        inside_type.serializeBinary(temp, serializer);
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:92]: we have saved default value instead of null, so don't need this `if` here:
```java
inside_type.serializeBinary(dict.get(i), serializer);
```

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 3]
```diff
@@ -27,23 +28,39 @@ public class ColumnLowCardinality extends AbstractColumn {
...
     }
 
     @Override
     public void write(Object object) throws IOException, SQLException {
-        long value = dict.indexOf(object);
-        if (value != -1) { 
-            indexes.add(value);
+        if (object == null) {
+            if (nested_is_nullable) {
+                indexes.add(0l);
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:49]: `0` ?

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 4]
```diff
@@ -27,23 +28,39 @@ public class ColumnLowCardinality extends AbstractColumn {
...
 
     public ColumnLowCardinality(String name, DataTypeLowCardinality type, Object[] values) {
         super(name, type, values);
         indexes = new ArrayList<>();
         dict = new ArrayList<>();
         data = ColumnFactory.createColumn(null, type.getNestedTypes(), null);
+        nested_is_nullable = type.getNestedTypes().nullable();
+        if (nested_is_nullable) {
+            dict.add(type.getNestedTypes().defaultValue());
+            dict.add(type.getNestedTypes().defaultValue());
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:41]: Add a note here: `If a nested type is nullable, always add two hard dictionary keys in front: [0]: null, [1]: default value`

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 5]
```diff
@@ -53,16 +70,37 @@ public void flushToSerializer(BinarySerializer serializer, boolean immediate) th
...
             serializer.writeLong(IndexType.UInt64.getValue() | IndexType.HasAdditionalKeysBit.getValue());
             serializer.writeLong(dict.size());
-            for (int i = 0; i < dict.size(); i++) {
-                data.write(dict.get(i));
+
+            if (data.type().nullable()) {
+
+                ColumnNullable type = (ColumnNullable) data;
+                DataTypeNullable inside_column_type = (DataTypeNullable) type.type();
+                IDataType inside_type = inside_column_type.getNestedDataType();
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:84]:
```suggestion
                DataTypeNullable nested_type = data.type();
                IDataType inner_type = nested_type.getNestedDataType();
```

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java (hunk 2 above)
Comment (yl-lisen) [reply timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:92]: Can we use `serializeBinaryBulk` instead of `loop serializeBinary`

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java [hunk 6]
```diff
@@ -119,20 +119,33 @@ public Object[] deserializeBinaryBulk(int rows, BinaryDeserializer deserializer)
...
             if (version != this.version) {
                 throw new SQLException("version error in type low_cardinality");
             }
 
             Long index_type = deserializer.readLong() & IndexTypeMask;
             Long key_nums = deserializer.readLong();
-            Object[] dictionary = getNestedTypes().deserializeBinaryBulk(key_nums.intValue(), deserializer);
+            Object[] dictionary = new Object[key_nums.intValue()];
+
+            if (getNestedTypes().nullable()) {
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java:132]: use `nested_is_nullable`

**Review by yl-lisen — APPROVED** [review]
