### PR TITLE
Fix the problem of map(low_cardinality) and tuple(low_cardinality)

### LINKED ISSUE #50: Problem existed in nested LowCardinality types, like array(low_cardinality(...))
When using low_cardinality decoration inside a complex datatype, there will be error and the insertion will fail.
Related code:
```
 @Test
    public void testMoreNestedType() throws Exception {
        withStatement(statement -> {
            statement.execute("DROP STREAM IF EXISTS nested_test");
            statement.execute(
                    "CREATE STREAM IF NOT EXISTS nested_test (value array(array(low_cardinality(int)))) Engine=Memory()");

            Integer rowCnt = 300;
            try (PreparedStatement pstmt = statement.getConnection().prepareStatement(
                    "INSERT INTO nested_test (value) values(?);")) {
                for (int i = 0; i < rowCnt; i++) {
                    // array of array
                    Array innerArray1 = statement.getConnection().createArrayOf("low_cardinality(int32)", new Object[]{1, 2, 3});
                    Array innerArray2 = statement.getConnection().createArrayOf("low_cardinality(int32)", new Object[]{4, 5, 6});
                    pstmt.setObject(1, statement.getConnection().createArrayOf("array(low_cardinality(int32))", new Object[]{innerArray1, innerArray2}));
                    pstmt.addBatch();
                }
                pstmt.executeBatch();
            }

            ResultSet rs = statement.executeQuery("SELECT * FROM nested_test;");
           // System.out.println("rs: " + rs.getRow());
            int size = 0;
            while (rs.next()) {
                size++;
                // array of array
                Array array = rs.getArray(1);
                Object[] arrayValue = (Object[]) array.getArray();
                assertEquals(arrayValue.length, 2);
                Array innerArray1 = (Array) arrayValue[0];
                Object[] innerArrayValue1 = (Object[]) innerArray1.getArray();
                assertEquals(innerArrayValue1.length, 3);
                assertEquals(innerArrayValue1[0], 1);
                assertEquals(innerArrayValue1[1], 2);
                assertEquals(innerArrayValue1[2], 3);
                Array innerArray2 = (Array) arrayValue[1];
                Object[] innerArrayValue2 = (Object[]) innerArray2.getArray();
                assertEquals(innerArrayValue2.length, 3);
                assertEquals(innerArrayValue2[0], 4);
                assertEquals(innerArrayValue2[1], 5);
                assertEquals(innerArrayValue2[2], 6);

            }
            assertEquals(size, rowCnt);
            statement.execute("DROP STREAM IF EXISTS nested_test");
        });
    }


%TESTC  1 v2
%TSTTREE2,com.timeplus.jdbc.type.LowCardinalityTypeTest,true,1,false,1,LowCardinalityTypeTest,,[engine:junit-jupiter]/[class:com.timeplus.jdbc.type.LowCardinalityTypeTest]
%TSTTREE3,testMoreNestedType(com.timeplus.jdbc.type.LowCardinalityTypeTest),false,1,false,2,testMoreNestedType(),,[engine:junit-jupiter]/[class:com.timeplus.jdbc.type.LowCardinalityTypeTest]/[method:testMoreNestedType()]
%TESTS  3,testMoreNestedType(com.timeplus.jdbc.type.LowCardinalityTypeTest)

%ERROR  3,testMoreNestedType(com.timeplus.jdbc.type.LowCardinalityTypeTest)
%TRACES 
com.timeplus.exception.TimeplusSQLException: DB::ExceptionDB::Exception: Invalid version for SerializationLowCardinality key column.. Stack trace:


        at com.timeplus.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:33)
        at com.timeplus.protocol.Response.readFrom(Response.java:35)
        at com.timeplus.client.NativeClient.receiveResponse(NativeClient.java:207)
        at com.timeplus.client.NativeClient.receiveEndOfStream(NativeClient.java:158)
        at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:294)
        at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.executeBatch(TimeplusPreparedInsertStatement.java:164)
        at com.timeplus.jdbc.type.LowCardinalityTypeTest.lambda$2(LowCardinalityTypeTest.java:221)
        at com.timeplus.jdbc.AbstractITestConnectDB.withStatement(AbstractITestConnectDB.java:137)
        at com.timeplus.jdbc.AbstractITestConnectDB.lambda$0(AbstractITestConnectDB.java:142)
        at com.timeplus.jdbc.AbstractITestConnectDB.withNewConnection(AbstractITestConnectDB.java:125)
        at com.timeplus.jdbc.AbstractITestConnectDB.withStatement(AbstractITestConnectDB.java:142)
        at com.timeplus.jdbc.type.LowCardinalityTypeTest.testMoreNestedType(LowCardinalityTypeTest.java:206)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
        at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
        Suppressed: java.sql.SQLException: Call getSampleBlock before insert.
                at com.timeplus.misc.Validate.isTrue(Validate.java:41)
                at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:289)
                at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.close(TimeplusPreparedInsertStatement.java:177)
                at com.timeplus.jdbc.type.LowCardinalityTypeTest.lambda$2(LowCardinalityTypeTest.java:222)
                ... 72 more

%TRACEE 

%TESTE  3,testMoreNestedType(com.timeplus.jdbc.type.LowCardinalityTypeTest)
%RUNTIME738
```

### PR DESCRIPTION
**Pull request by Jasmine-ge**
Fix some of the existed problems of nested low_cardinality types. close #50

### CODE REVIEW

**Comment by yl-lisen** [comment]
need revisit the interface:
```
Column::flushToSerializer
{
    serializeBulkPrefix();
    serializeBulk();
    serializeBulkSuffix();
}
```

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/Column.java [hunk 1]
```diff
@@ -33,13 +33,20 @@ public void write(Object object) throws IOException, SQLException {
 
     @Override
     public void flushToSerializer(BinarySerializer serializer, boolean now) throws IOException, SQLException {
-        if (isExported()) {
-            serializer.writeUTF8StringBinary(name);
-            serializer.writeUTF8StringBinary(type.name());
-        }
+        super.flushToSerializer(serializer, now);
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/Column.java:37]: don't need override

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/Column.java [hunk 2]
```diff
@@ -33,13 +33,20 @@ public void write(Object object) throws IOException, SQLException {
...
+
+    @Override
+    public void SerializeBulkPrefix(BinarySerializer serializer) { }
 
+    @Override
+    public void SerializeBulkSuffix(BinarySerializer serializer) { }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/Column.java:43]: don't need override if is default implementation

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 3]
```diff
@@ -70,28 +70,21 @@ public void write(Object object) throws IOException, SQLException {
     }
 
     @Override
-    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws IOException, SQLException {
-        if (isExported()) {
-            serializer.writeUTF8StringBinary(name);
-            serializer.writeUTF8StringBinary(type.name());
+    public void SerializeBulk(BinarySerializer serializer, boolean immediate) throws IOException, SQLException {
+        /// The data layout: [version][index_type][dictionary][indexes]
+        // serializer.writeLong(version);
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:75]: remove this line

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 4]
```diff
@@ -70,28 +70,21 @@ public void write(Object object) throws IOException, SQLException {
     }
 
     @Override
-    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws IOException, SQLException {
-        if (isExported()) {
-            serializer.writeUTF8StringBinary(name);
-            serializer.writeUTF8StringBinary(type.name());
+    public void SerializeBulk(BinarySerializer serializer, boolean immediate) throws IOException, SQLException {
+        /// The data layout: [version][index_type][dictionary][indexes]
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:74]: update comments

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 5]
```diff
@@ -103,4 +96,21 @@ public void setColumnWriterBuffer(ColumnWriterBuffer buffer) {
...
+    }
+
+    @Override
+    public void SerializeBulkSuffix(BinarySerializer serializer) {
+    }
+
+    @Override
+    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws SQLException, IOException {
+        super.flushToSerializer(serializer, immediate);
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:113]: remove

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnMap.java [hunk 6]
```diff
@@ -96,4 +92,20 @@ public void clear() {
...
+    @Override
+    public void SerializeBulkPrefix(BinarySerializer serializer) throws SQLException, IOException {
+        for (IColumn data : columnDataArray) {
+            data.SerializeBulkPrefix(serializer);
+        }
+    }
+
+    @Override
+    public void SerializeBulkSuffix(BinarySerializer serializer) {
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnMap.java:105]: need call nested data.SerializeBulkSuffix()

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnMap.java [hunk 7]
```diff
@@ -96,4 +92,20 @@ public void clear() {
...
+
+    @Override
+    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws SQLException, IOException {
+        super.flushToSerializer(serializer, immediate);
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnMap.java:110]: remove

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnNullable.java [hunk 8]
```diff
@@ -66,4 +61,19 @@ public void setColumnWriterBuffer(ColumnWriterBuffer buffer) {
...
+
+    @Override
+    public void SerializeBulkSuffix(BinarySerializer serializer) {
+        
+    }
+
+    @Override
+    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws SQLException, IOException {
+        super.flushToSerializer(serializer, immediate);
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnNullable.java:78]: remove

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnTuple.java [hunk 9]
```diff
@@ -45,16 +45,16 @@ public void write(Object object) throws IOException, SQLException {
...
-    public void flushToSerializer(BinarySerializer serializer, boolean now) throws SQLException, IOException {
-        if (isExported()) {
-            serializer.writeUTF8StringBinary(name);
-            serializer.writeUTF8StringBinary(type.name());
-        }
+    public void SerializeBulk(BinarySerializer serializer, boolean now) throws SQLException, IOException {
+        // if (isExported()) {
+        //     serializer.writeUTF8StringBinary(name);
+        //     serializer.writeUTF8StringBinary(type.name());
+        // }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnTuple.java:52]: remove

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnTuple.java [hunk 10]
```diff
@@ -74,4 +74,21 @@ public void setColumnWriterBuffer(ColumnWriterBuffer buffer) {
...
+    public void SerializeBulkPrefix(BinarySerializer serializer) throws SQLException, IOException {
+        for (IColumn data : columnDataArray) {
+            data.SerializeBulkPrefix(serializer);
+        }
+    }
+
+    @Override
+    public void SerializeBulkSuffix(BinarySerializer serializer) {
+        
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnTuple.java:88]: need call nested column.SerializeBulkSuffix

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnTuple.java [hunk 11]
```diff
@@ -74,4 +74,21 @@ public void setColumnWriterBuffer(ColumnWriterBuffer buffer) {
...
+
+    @Override
+    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws SQLException, IOException {
+        super.flushToSerializer(serializer, immediate);
+    }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnTuple.java:93]: remove

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/IColumn.java [hunk 12]
```diff
@@ -31,6 +31,9 @@ public interface IColumn {
 
     void write(Object object) throws IOException, SQLException;
 
+
+    void SerializeBulkPrefix(BinarySerializer serializer) throws IOException, SQLException;
+
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/IColumn.java:36]: remove interface SerializeBulkXXX ...

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/type/DataTypeBool.java [hunk 13]
```diff
@@ -12,59 +12,65 @@
...
+    @Override
+    public boolean isSigned() {
+        return true;
+    }
+
+    @Override
+    public void deserializeBinaryPrefix(int rows, BinaryDeserializer deserializer) throws SQLException, IOException { }
+    
+    @Override
+    public void deserializeBinarySuffix(int rows, BinaryDeserializer deserializer) throws SQLException, IOException { }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/type/DataTypeBool.java:75]: remove

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/type/DataTypeDate.java [hunk 14]
```diff
@@ -97,4 +97,10 @@ public LocalDate deserializeText(SQLLexer lexer) throws SQLException {
 
         return LocalDate.of(year, month, day);
     }
+
+    @Override
+    public void deserializeBinaryPrefix(int rows, BinaryDeserializer deserializer) throws SQLException, IOException { }
+    
+    @Override
+    public void deserializeBinarySuffix(int rows, BinaryDeserializer deserializer) throws SQLException, IOException { }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/type/DataTypeDate.java:105]: remove

**Review by yl-lisen — APPROVED** [review]
