### PR TITLE
Bugfix/issue 35 invalid version for lowcardinality keys

### LINKED ISSUE #35: Invalid version for SerializationLowCardinality key column.. Stack trace:
### Environment

- OS version: Ubuntu
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
Exception in thread "main" com.timeplus.exception.TimeplusSQLException: DB::ExceptionDB::Exception: Invalid version for SerializationLowCardinality key column.. Stack trace:


	at com.timeplus.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:33)
	at com.timeplus.protocol.Response.readFrom(Response.java:35)
	at com.timeplus.client.NativeClient.receiveResponse(NativeClient.java:207)
	at com.timeplus.client.NativeClient.receiveEndOfStream(NativeClient.java:158)
	at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:294)
	at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.executeBatch(TimeplusPreparedInsertStatement.java:155)
	at examples.BatchQuery.main(BatchQuery.java:47)
	Suppressed: java.sql.SQLException: Call getSampleBlock before insert.
		at com.timeplus.misc.Validate.isTrue(Validate.java:41)
		at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:289)
		at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.close(TimeplusPreparedInsertStatement.java:168)
		at examples.BatchQuery.main(BatchQuery.java:33)
[BatchQuery 2.java.zip](https://github.com/user-attachments/files/16245289/BatchQuery.2.java.zip)

```

### PR DESCRIPTION
**Pull request by Jasmine-ge**
close #35

### CODE REVIEW

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+        indexes = new ArrayList<>();
+        dict = new ArrayList<>();
+        data = ColumnFactory.createColumn(null, type.getNestedTypes(), null);
+    }
+
+    @Override
+    public void write(Object object) throws IOException, SQLException {
+        boolean found = false;
+        for (Object obj : dict) {
+            if (obj != null && obj.equals(object)) {
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:42]: we can remove `obj != null`  since the elements should always be not null.

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+                found = true;
+                break;
+            }
+        }
+        if (found) {
+            long value = dict.indexOf(object);
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:48]: can we use `indexOf` to check whether object is existed

Comment (yl-lisen) [reply timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:48]: for example:
```java
long value = dict.indexOf(object);
if (value == <invalid_idx>) {
    indexes.add(dict.length());
    dict.add(object);
}
else {
    indexes.add(value);
}
```

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+    }
+
+    @Override
+    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws IOException, SQLException {
+        if (isExported()) {
+            serializer.writeUTF8StringBinary(name);
+            serializer.writeUTF8StringBinary(type.name());
+        }
+        if (immediate) {
+            serializer.writeLong(version); //  add version
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:65]: we add add format layout comment at first:
```java
/// The data layout: [version][index_type][dictionary][indexes]
```

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+            serializer.writeLong(IndexType.UInt64.getValue() | IndexType.HasAdditionalKeysBit.getValue()); //  need to judge the type as additional key
+            serializer.writeLong(dict.size()); //  give dictionary type size
+            for (int i = 0; i < dict.size(); i++) {
+                data.write(dict.get(i));
+            }
+            data.flushToSerializer(serializer, true);
+
+            serializer.writeLong(indexes.size()); //  give index type size
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:73]: remove useless comment

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    @Override
+    public void flushToSerializer(BinarySerializer serializer, boolean immediate) throws IOException, SQLException {
+        if (isExported()) {
+            serializer.writeUTF8StringBinary(name);
+            serializer.writeUTF8StringBinary(type.name());
+        }
+        if (immediate) {
+            serializer.writeLong(version); //  add version
+            serializer.writeLong(IndexType.UInt64.getValue() | IndexType.HasAdditionalKeysBit.getValue()); //  need to judge the type as additional key
+            serializer.writeLong(dict.size()); //  give dictionary type size
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/ColumnLowCardinality.java:67]: remove useless comment

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java [hunk 6]
```diff
@@ -104,12 +106,46 @@ public Object deserializeBinary(BinaryDeserializer deserializer) throws SQLExcep
...
+        if (rows==0) {
+            Object[] data = nestedDataType.deserializeBinaryBulk(rows, deserializer);
+            return data;
+        }
+        else {
+            Long version = deserializer.readLong(); 
+            if (version != this.version) {
+                throw new SQLException("version error in type low_cardinality");
+            }
+            Long index_type = deserializer.readLong() & 0b11111111; //  decide what type it is
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java:118]: use constant or enum type instead of  `0b11111111`

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java [hunk 7]
```diff
@@ -104,12 +106,46 @@ public Object deserializeBinary(BinaryDeserializer deserializer) throws SQLExcep
...
+                    data[i]=dictionary[deserializer.readShort()];
+                }
+                else if (index_type == IndexType.UInt32.getValue()) {
+                    data[i]=dictionary[deserializer.readInt()];
+                }
+                else {
+                    data[i]=dictionary[(int) deserializer.readLong()];
+                }
+                
+            }
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java:137]: a better way to avoid compare index_type more times:
```java
DataType type;
if (index_type == uint8)
    type = new ... DataTypeUInt8 (or DataTypeFactory.get("uint8");
else (index_type == uint16)
  ...

data = type.deserializeBinaryBulk(rows);
```

File: timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java [hunk 8]
```diff
@@ -101,39 +106,47 @@ public void serializeBinaryBulk(Object[] data, BinarySerializer serializer) thro
...
-            Long index_type = deserializer.readLong() & 0b11111111; //  decide what type it is
+
+            Long index_type = deserializer.readLong() & IndexTypeMask;
             Long key_nums = deserializer.readLong();
-            Object[] dictionary = nestedDataType.deserializeBinaryBulk(key_nums.intValue(), deserializer);
+            Object[] dictionary = getNestedTypes().deserializeBinaryBulk(key_nums.intValue(), deserializer);
+
             Long row_nums = deserializer.readLong();
+            if (row_nums != rows) {
+                throw new SQLException("unexpected error in low_cardinality row reading");
```
Comment (yl-lisen) [inline timeplus-native-jdbc/src/main/java/com/timeplus/data/type/complex/DataTypeLowCardinality.java:130]: `read unexpected rows in low_cardinality, expected {} , actual {}`

**Review by yl-lisen — APPROVED** [review]
